export const FETCH_CARDS_REQUEST = "FETCH_CARDS_REQUEST";
export const FETCH_CARDS_SUCCESS = "FETCH_CARDS_SUCCESS";
export const FETCH_CARDS_ERROR = "FETCH_CARDS_ERROR";
export const FLIP_CARD = "FLIP_CARD";
export const MATCHED_CARDS = "MATCH_CARDS";
export const FLIP_RESET = "FLIP_RESET";
export const UPDATE_UNIQUE = "UPDATE_UNIQUE";
export const UPDATE_CARDS = "UPDATE_CARDS";